### ISSUE TITLE
(에러) CUDA out of memory. 문의 드립니다.

### ISSUE THREAD

**Issue by jyseojys** [kakaobrain/karlo#1]
초보자이므로 문의 내용이 불충분하더라도 양해 부탁드립니다.
[관련 예제](https://github.com/kakaobrain/karlo#gradio-demo-t2i-and-image-variation) 실행하는 중에 "CUDA out of memory." 에러가 발생하여 문의 드리며, 해결방법 조언해 주시면 고맙겠습니다.

### (실행 환경)
-ubuntu          18.04
-GPU (nviDIA GeForce RTX 3090(Memory : 24G))
-python          3.8
-black             22.6.0         
-pytorch          1.10.0  / 1.12.1 (2개버전 각각 진행 - 결과 동일)
-torchvision     0.11.0  / 0.13.1 (2개버전 각각 진행 - 결과 동일)
-einops           0.6.0        
-omegaconf    2.2.3           
-matplotlib      3.3.4           
-gradio           3.12.0 

### (예제 실행)
**> python demo/product_demo.py --host 127.0.0.1 --port 6021 --root-dir /home/jyseo/project/kakaobrain_karlo/karlo**     

**-(예제 결과)**
  /home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/serialization.py:707: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
INFO:root:Loading prior: prior-ckpt-step=01000000-of-01000000.ckpt
INFO:root:done.
INFO:root:Loading decoder: decoder-ckpt-step=01000000-of-01000000.ckpt
INFO:root:done.
INFO:root:Loading SR(64->256): improved-sr-ckpt-step=1.2M.ckpt
INFO:root:done.
Running on local URL:  http://127.0.0.1:6021

To create a public link, set share=Ture in launch().
![image](https://user-images.githubusercontent.com/57515713/205444368-484e6644-9bd2-46bf-b760-27ec54f13d08.png)

(에러)
----------------------------------------------------------------------------------------------------
text_input: a black porcelain in the shape of pikachu
prior_sm: 25
prior_cf_scale: 4
decoder_sm: 25
decoder_cf_scale: 8
sr_sm: 7
seed: 0
max_bsz: 4
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/demo/components.py", line 171, in _sample
    for k, out in enumerate(output_generator):
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/sampler/t2i.py", line 150, in __call__
    for k, out in enumerate(images_256_outputs):
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/models/sr_64_256.py", line 86, in forward
    for x in sample_outputs:
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/diffusion/gaussian_diffusion.py", line 631, in p_sample_loop_progressive_for_improved_sr
    out = self.p_sample(
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/diffusion/gaussian_diffusion.py", line 483, in p_sample
    out = self.p_mean_variance(
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/diffusion/respace.py", line 97, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/diffusion/gaussian_diffusion.py", line 338, in p_mean_variance
    model_output = model(x, t, **model_kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/diffusion/respace.py", line 107, in wrapped
    return model(
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/unet.py", line 691, in forward
    return super().forward(x, timesteps, **kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/unet.py", line 665, in forward
    h = module(h, emb)
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/unet.py", line 44, in forward
    x = layer(x, emb)
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/unet.py", line 223, in forward
    h = self.out_layers(h)
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jyseo/project/kakaobrain_karlo/karlo/karlo/modules/nn.py", line 18, in forward
    y = super().forward(x.float()).to(x.dtype)
RuntimeError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 23.70 GiB total capacity; 20.26 GiB already allocated; 635.88 MiB free; 21.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### (에러메시지)
**RuntimeError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 23.70 GiB total capacity; 20.26 GiB already allocated; 635.88 MiB free; 21.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF**

### (조치 사항) --> karlo/sampler/t2i.py 코드 수정 (기존)[256, 256],   --> (변경)[128, 128],

            """ Upsample 64x64 to 256x256 """
            images_256 = TVF.resize(
                images_64,
                #(기존)[256, 256],  
                #(변경)
                [128, 128],
                interpolation=InterpolationMode.BICUBIC,
                antialias=True,
            )

**### (조치 사항 결과)**  -->###  **에러 없으나, 결과물은 미완성**

> python demo/product_demo.py --host 127.0.0.1 --port 6023 --root-dir /home/jyseo/project/kakaobrain_karlo/karlo
/home/jyseo/miniconda2/envs/mapnet_py38/lib/python3.8/site-packages/torch/serialization.py:707: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
INFO:root:Loading prior: prior-ckpt-step=01000000-of-01000000.ckpt
INFO:root:done.
INFO:root:Loading decoder: decoder-ckpt-step=01000000-of-01000000.ckpt
INFO:root:done.
INFO:root:Loading SR(64->256): improved-sr-ckpt-step=1.2M.ckpt
INFO:root:done.
Running on local URL:  http://127.0.0.1:6023

To create a public link, set share=True in launch().

----------------------------------------------------------------------------------------------------
text_input: a black porcelain in the shape of pikachu
prior_sm: 25
prior_cf_scale: 4
decoder_sm: 25
decoder_cf_scale: 8
sr_sm: 7
seed: 0
max_bsz: 4
INFO:root:Generation done. a black porcelain in the shape of pikachu -- 7.740963secs
----------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/57515713/205445680-403fc0a9-4ee7-4cec-b27f-4eb409189738.png)

낮은 퀄리티 출력됨.

**Comment by donghoonlee04** [comment]
Thank you for your interest in karlo.
For OOM errors, you can reduce --max_bsz to 1 or 2 and run the demo.
https://github.com/kakaobrain/karlo/blob/e105e7643c4e9f30b1b17c7e4354d8474455dcb3/demo/product_demo.py#L92

**Comment by jyseojys** [comment]
--max_bsz  = 1, 경우 에러 없이 성공했습니다. 감사합니다.
