### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by jasonmhead** [kakaobrain/karlo#12]
I set os.environ["CUDA_VISIBLE_DEVICES"]="1" in components.py to use my second gpu and when I try to create a image via the gradio interface I get:
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

```set CUDA_VISIBLE_DEVICES=1```
in the Anaconda prompt terminal before running the script doesn't fix the error.

And ```torch.cuda.set_device(1)``` after the torch import causes
```RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper__index_select)```

I've changed ```cpu``` to ```"cuda"``` or ```cuda()``` where ```"cpu"``` or ```cpu()``` was in the repo files, but the error is still thrown when I try to run the model 
(gradio started via ```python demo/product_demo.py --host 0.0.0.0 --port 8085  --root-dir .```)

Any suggestions as to what I should change to get everything on the specified GPU?
Suggested solutions that would fit in under 24GB of VRAM?

-------------------------

edit:
I tried 

```
set 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
```

with 

```
timestep_map_tensor = th.tensor(timestep_map)
cuda_device = th.device("cuda")
timestep_map_tensor = timestep_map_tensor.to(cuda_device)
self.register_buffer("timestep_map", timestep_map_tensor, persistent=False)

```

in respace.py, and was able to load things, and the image started generating :)
but ran out of vram

-------------------------------

Full output:
```
Exception in thread Thread-2 (_sample):
Traceback (most recent call last):
  File "C:\Users\Jason\.conda\envs\karlo\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Jason\.conda\envs\karlo\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\demo\components.py", line 174, in _sample
    for k, out in enumerate(output_generator):
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\sampler\t2i.py", line 116, in __call__
    img_feat = self._prior(
  File "C:\Users\Jason\.conda\envs\karlo\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\models\prior_model.py", line 127, in forward
    sample = sample_fn(
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\modules\diffusion\gaussian_diffusion.py", line 533, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\modules\diffusion\gaussian_diffusion.py", line 584, in p_sample_loop_progressive
    out = self.p_sample(
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\modules\diffusion\gaussian_diffusion.py", line 483, in p_sample
    out = self.p_mean_variance(
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\modules\diffusion\respace.py", line 97, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\modules\diffusion\gaussian_diffusion.py", line 338, in p_mean_variance
    model_output = model(x, t, **model_kwargs)
  File "C:\Users\Jason\Documents\machine_learning\image_ML\karlo\karlo\modules\diffusion\respace.py", line 108, in wrapped
    x, self.timestep_map[ts].to(device=ts.device, dtype=ts.dtype), **kwargs
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by jasonmhead** [comment]
-------------------------
I tried 

```
set 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
```

with 

```
timestep_map_tensor = th.tensor(timestep_map)
cuda_device = th.device("cuda")
timestep_map_tensor = timestep_map_tensor.to(cuda_device)
self.register_buffer("timestep_map", timestep_map_tensor, persistent=False)

```

in respace.py, and was able to load things, and the image started generating :)
but ran out of vram

-------------------------------

**Comment by jasonmhead** [comment]
lowering the "maximum batch size" I am able to successfully run things :)
after those two changes

**Comment by saehoonkim** [comment]
@jasonmhead thanks for reporting this issue. @jmkim0309 could you make a PR to fix this issue? many thanks!

**Comment by Alfred-Duncan** [comment]
https://github.com/kakaobrain/karlo/issues/8
I met that problem before, and I change my env.
maybe this can work:

x, self.timestep_map[ts.to("cpu")].to(device=ts.device, dtype=ts.dtype), **kwargs
