### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu). And anybody kown how to generate on multiple GPUs?

### ISSUE THREAD

**Issue by Alfred-Duncan** [kakaobrain/karlo#8]
When I use
CUDA_VISIBLE_DEVICES=0 python demo/product_demo.py --host 0.0.0.0 --port 9870 --root-dir ./models/
(env:python3.10.8   torch==1.13.0+cu116)
and I entered the gradio UI, but when I generate, the error below happend.

But when I change another env:python3.8.13  torch==1.12.1+cu113
It works but OOM...... Seems 24Gb not enough for him......
U kown I have four Nvidia3090, so I want to know if there is any way to generate on multiple GPUs?

/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/serialization.py:779: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
INFO:root:Loading prior: prior-ckpt-step=01000000-of-01000000.ckpt
INFO:root:done.
INFO:root:Loading decoder: decoder-ckpt-step=01000000-of-01000000.ckpt
INFO:root:done.
INFO:root:Loading SR(64->256): improved-sr-ckpt-step=1.2M.ckpt
INFO:root:done.
Running on local URL:  http://0.0.0.0:9870

To create a public link, set `share=True` in `launch()`.
----------------------------------------------------------------------------------------------------
text_input: a dog
prior_sm: 25
prior_cf_scale: 4
decoder_sm: 25
decoder_cf_scale: 8
sr_sm: 7
seed: 0
max_bsz: 4
Exception in thread Thread-2 (_sample):
Traceback (most recent call last):
  File "/root/anaconda3/envs/py310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/py310/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tongange/karlo-main/demo/components.py", line 171, in _sample
    for k, out in enumerate(output_generator):
  File "/home/tongange/karlo-main/karlo/sampler/t2i.py", line 109, in __call__
    img_feat = self._prior(
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tongange/karlo-main/karlo/models/prior_model.py", line 120, in forward
    sample = sample_fn(
  File "/home/tongange/karlo-main/karlo/modules/diffusion/gaussian_diffusion.py", line 533, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/tongange/karlo-main/karlo/modules/diffusion/gaussian_diffusion.py", line 584, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/tongange/karlo-main/karlo/modules/diffusion/gaussian_diffusion.py", line 483, in p_sample
    out = self.p_mean_variance(
  File "/home/tongange/karlo-main/karlo/modules/diffusion/respace.py", line 97, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/tongange/karlo-main/karlo/modules/diffusion/gaussian_diffusion.py", line 338, in p_mean_variance
    model_output = model(x, t, **model_kwargs)
  File "/home/tongange/karlo-main/karlo/modules/diffusion/respace.py", line 108, in wrapped
    x, self.timestep_map[ts].to(device=ts.device, dtype=ts.dtype), **kwargs
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by donghoonlee04** [comment]
Could you try to modify
https://github.com/kakaobrain/karlo/blob/0b5dbb0c9f34363921a5c3bf2a78dfe8e3ad6ceb/karlo/modules/diffusion/respace.py#L108
to
`x, self.timestep_map[ts.to("cpu")].to(device=ts.device, dtype=ts.dtype), **kwargs`
and re run?

**Comment by donghoonlee04** [comment]
For OOM errors, you can reduce --max_bsz to 1 or 2 and run the demo.

**Comment by Alfred-Duncan** [comment]
yeah I try to fix the
x, self.timestep_map[ts.to("cpu")].to(device=ts.device, dtype=ts.dtype), **kwargs
but it didn't work, and I change another env

**Comment by Alfred-Duncan** [comment]
it's strange for that,
because when I train the stable diffusion, also has this problem, and I stil change the env to solve it,
I don't konw the exactly reason......

**Comment by Alfred-Duncan** [comment]
Sure I will change the batch size try that again!

**Comment by Alfred-Duncan** [comment]
> Sure I will change the batch size try that again!

when the batch size is one, my 3090 need  24041MiB / 24576MiB to generate
